name: release

on:
  push:
    tags:
      - 'v**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-publish
  cancel-in-progress: true

jobs:
  build-n-publish:
    runs-on: ubuntu-20.04
    #if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install build tools
        run: pip install build twine wheel
      - name: Build DiffSynth
        run: python -m build
      - name: Smoke test built package
        run: |
          pip install dist/*.whl --no-deps
          python -c "import diffsynth; from diffsynth.version import __version__; print(f'Successfully imported diffsynth {__version__}')"
      - name: Publish package to PyPI
        run: |
          twine upload dist/* --skip-existing -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
